server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/creative_market?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    task:
      scheduling:
        #      调度线程池名称前缀
        thread-name-prefix: spring_boot_task_
        #      任务调度线程池大小，默认1
        pool:
          size: 10
        shutdown:
          #        线程池关闭时等待所有任务完成
          await-termination: false
          #        调度线程关闭前最大等待时间，确保最后一定关闭
          await-termination-period: 10s
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  profiles:
    active: dev
  elasticsearch:
    uris: http://localhost:9200
  rabbitmq:
    host: localhost
    port: 5672

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

creativeMarket:
  filePath: D:\img
  shopImage: D:\img\shopImage
  detailsImage: D:\img\shop_details_image
  iconImage: D:\img\iconImage
  discoverImage: D:\img\discover_image


