server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/creative_market
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  profiles:
    active: dev
  elasticsearch:
    uris: http://localhost:9200
  rabbitmq:
    host: localhost
    port: 5672

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

creativeMarket:
  filePath: D:\img
  shopImage: D:\img\shopImage
  detailsImage: D:\img\shop_details_image
  iconImage: D:\img\iconImage
